import Banner from '@/components/LandingPage/Banner'
import Services from '@/components/LandingPage/Services'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Owlify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
      <Banner/>
      <Services />
      
      </main>
    </>
  )
}
