import Banner from '@/components/LandingPage/Banner'
import Services from '@/components/LandingPage/Services'
import Head from 'next/head'
import Image from 'next/image'
import TryNow from '@/components/common/TryNow'
import jsonData from '../components/LandingPage/data.json'

export default function Home({data}) {
  console.log(data)
  return (
    <>
      <Head>
        <title>Owlify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="">
      <Banner/>
      <div className='row p-2 headings text-center'>
      <div><>Our Services</></div>  
      </div>

      <Services jsonData={data}/>
      <TryNow />
      </main>
    </>
  )
}

export const getStaticProps = (async () => {
  const json = await jsonData
  console.log(json)
  return {
    props: {
      data:json
    },
  };
})