import Banner from '@/components/LandingPage/Banner'
import Services from '@/components/LandingPage/Services'
import Head from 'next/head'
import Image from 'next/image'
import TryNow from '@/components/common/TryNow'
import jsonData from '../components/LandingPage/data.json'
import Clients from '@/components/LandingPage/Clients'

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Owlify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="container-fluid p-0">
      <Banner/>
      <Services jsonData={data}/>
      <div className='row headings text-center'>
      <div><>Our Clients</></div>  
      <Clients/>
      </div>
      {/* <TryNow /> */}
      </main>
    </>
  )
}

export const getStaticProps = (async () => {
  const json = await jsonData
  return {
    props: {
      data:json
    },
  };
})